### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by mp1pro** [mongipong/jammmingFinalWithNewFeature#1]
### Criteria 1: Objective Section  
* _Score Level:_ 4/4
* _Comment(s):_ The objective is concise and straight to the point. Allowing the user to use the enter key for triggering the search function will improve the efficiency of the app. 
 
### Criteria 2: Background Section
* _Score Level:_ 4/4
* _Comment(s):_ The background section provides sound reasoning for the necessity of the proposed feature. The user interface and experience will also benefit substantially. 
 
### Criteria 3: Technical Design Section
* _Score Level:_ 4/4
* _Comment(s):_ The technical design presented is practical and follows the best practices for adding a keyboard function to the code.

### Criteria 4: Caveats Section
* _Score Level:_ 4/4
* _Comment(s):_ Very good taking into consideration the other key events that could have been used. The only drawback with onKeyPress is that it can be fired repeatedly if the user holds down the enter key. In terms of best practice, the best choice is onKeyUp. ref: [https://javascript.info/keyboard-events](https://javascript.info/keyboard-events)

### Overall Score: 16/16

The overall feature request was well thought out and on point.

**Comment by mongipong** [comment]
Thanks😊
